#ifndef __AS_FFXI_ENUMS_H_INCLUDED__
#define __AS_FFXI_ENUMS_H_INCLUDED__

#if defined (_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

namespace Ashita {
    namespace FFXI {
        /**
         * FFXI Enumerations
         */
        enum class TARGETTYPE : int32_t
        {
            NONE = 0,
            SELF = 1,
            PLAYER = 2,
            PARTY = 3,
            ALLIANCE = 4,
            NPC = 5,
            ENEMY = 6,
            UNKNOWN_1 = 7,
            UNKNOWN_2 = 8,
            PET = 9,
            PET_MASTER = 10,
            PET_PARTY = 11,
            ENEMY_PARTY = 12
        };

        enum class JOBS : uint8_t
        {
            NONE = 0,
            WAR = 1,
            MNK = 2,
            WHM = 3,
            BLM = 4,
            RDM = 5,
            THF = 6,
            PLD = 7,
            DRK = 8,
            BST = 9,
            BRD = 10,
            RNG = 11,
            SAM = 12,
            NIN = 13,
            DRG = 14,
            SMN = 15,
            BLU = 16,
            COR = 17,
            PUP = 18,
            DNC = 19,
            SCH = 20,
            GEO = 21,
            RUN = 22,
        };

        enum class ABILITIES : uint16_t
        {
            FIGHT = 0,
            PROVOKE = 5,
            HUNDRED_FISTS = 30,
            BENEDICTION = 37,
            MANAFONT = 45,
            CHAINSPELL = 53,
            PERFECT_DODGE = 61,
            INVINCIBLE = 69,
            BLOOD_WEAPON = 77,
            FAMILIAR = 85,
            MIJIN_GAKURE = 101,
            CALL_WYVERN = 109,
            ASTRAL_FLOW = 117,
            AZURE_LORE = 125,
            WILDCARD = 133,
            REPAIR = 141,
            TRANCE = 149,
            TABULA_RASA = 157,
            BOLSTER = 165,
            ELEMENTAL_SFORZO = 173,
            BERSERK = 4,
            DEFENDER = 8,
            AGGRESSOR = 9,
            FOCUS = 17,
            DODGE = 18,
            CHAKRA = 20,
            BOOST = 16,
            COUNTERSTANCE = 24,
            DIVINE_SEAL = 33,
            ELEMENTAL_SEAL = 41,
            SNEAK_ATTACK = 57,
            LARCENY = 62,
            TRICK_ATTACK = 58,
            ACCOMPLICE = 63,
            FEALTY = 67,
            SHIELD_BASH = 65,
            SENTINEL = 66,
            RAMPART = 70,
            COVER = 68,
            SOULEATER = 74,
            ARCANE_CIRCLE = 76,
            WEAPON_BASH = 73,
            LAST_RESORT = 75,
            CALL_BEAST = 81,
            PET_HEEL = 82,
            PET_STAY = 83,
            PET_ATTACK = 84,
            REWARD = 88,
            CHARM = 87,
            GAUGE = 86,
            TAME = 89,
            SOUL_VOICE = 93,
            STEADY_SHOT = 99,
            SHARPSHOT = 98,
            BARRAGE = 100,
            MEIKYO_SHISUI = 107,
            THIRD_EYE = 105,
            WARCRY = 10,
            MEDITATE = 106,
            HAGAKURE = 108,
            ANCIENT_CIRCLE = 111,
            JUMP = 110,
            HIGH_JUMP = 112,
            SUPER_JUMP = 113,
            SPIRIT_SURGE = 116,
            BLOOD_PACT_RAGE = 118,
            BLOOD_PACT_WARD = 119,
            CHAIN_AFFINITY = 127,
            BURST_AFFINITY = 126,
            UNBRIDLED_LEARNING = 124,
            PHANTOM_ROLL = 134,
            DOUBLE_UP = 130,
            BUST = 132,
            FOLD = 131,
            ACTIVATE = 142,
            OVERDRIVE = 140,
            FINISHING_MOVE_1 = 148,
            FINISHING_MOVE_2 = 147,
            FINISHING_MOVE_3 = 146,
            FINISHING_MOVE_4 = 145,
            FINISHING_MOVE_5 = 144,
            CURING_WALTZ = 153,
            CURING_WALTZ_II = 152,
            CURING_WALTZ_III = 151,
            CURING_WALTZ_IV = 150,
            CURING_WALTZ_V = 154,
            HEALING_WALTZ = 155,
            DRAINING_SAMBA = 161,
            ASPIR_SAMBA = 162,
            HASTE_SAMBA = 163,
            SPECTRAL_JIG = 156,
            BUILDING_FLOURISH = 164,
            DESPERATE_FLOURISH = 160,
            REVERSE_FLOURISH = 159,
            VIOLENT_FLOURISH = 158,
            WILD_FLOURISH = 159,
            CLIMACTIC_FLOURISH = 164,
            STRIKING_FLOURISH = 164,
            TERPSICHOREAN_FLOURISH = 164,
            RANDOM_DEAL = 135,
            SNAKES_EYE = 136,
            CROOKED_CARDS = 137,
            STRATEGEM = 166,
            LIGHT_ARTS = 167,
            DARK_ARTS = 168,
            PENURY = 169,
            PARSIMONY = 170,
            CELERITY = 171,
            ALACRITY = 172,
            ACCESSION = 169,
            MANIFESTATION = 170,
            EMBODY = 177,
            INDI_ACUMEN = 181,
            INDI_FURY = 178,
            INDI_FOCUS = 182,
            INDI_FADE = 183,
            INDI_BARRIER = 184,
            INDI_PRECISION = 179,
            INDI_ATTR = 185,
            INDI_REGEN = 180,
            INDI_REFRESH = 186,
            GEO_POISON = 191,
            GEO_FRAILTY = 187,
            GEO_FURY = 188,
            GEO_FADE = 189,
            GEO_VOIDANCE = 190,
            GEO_FOCUS = 192,
            GEO_LANGUOR = 193,
            GEO_WITHER = 194,
            GEO_ACUMEN = 195,
            GEO_TORPOR = 196,
            GEO_MALAISE = 197,
            GEO_SLOW = 198,
            GEO_PARALYSIS = 199,
            GEO_GRAVITY = 200,
            GEO_REFRESH = 201,
            GEO_REGEN = 202,
            GEO_STR = 203,
            GEO_DEX = 204,
            GEO_VIT = 205,
            GEO_AGI = 206,
            GEO_INT = 207,
            GEO_MND = 208,
            GEO_CHR = 209,
            RADIAL_ARCANA = 210,
            LIFE_CYCLE = 211,
            FULL_CIRCLE = 212,
            GREATER_COLURE = 213,
            ENTRUST = 214,
            LIEMENT = 215,
            VALLATION = 216,
            PFLUG = 217,
            GAMBIT = 218,
            RAYKE = 219,
            SWORDPLAY = 220,
            EMBOLDEN = 221,
            ONE_FOR_ALL = 222,
            VIVACIOUS_PULSE = 223,
            VALIANCE = 216,
            FOIL = 220
        };
    }; // namespace FFXI
}; // namespace Ashita

#endif // __AS_FFXI_ENUMS_H_INCLUDED__